#!/bin/bash

SAVEIFS=$IFS
IFS=$(echo -en "\n\b")

for app in "$@"
do
  app=${app/\//}
  path=`./path $app`
  for localfile in $(find $app -type f)
  do
    realfile=$path/${localfile#$app/}
    output=`diff -r --ignore-all-space $localfile $realfile`
    if [ $? -ne 0 ]; then
      echo
      echo "$localfile <=> $realfile"
      echo "$output"
    fi
  done
done

IFS=$SAVEIFS
