#!/bin/bash

if [ $# -eq 0 ]; then
  echo "Usage: ${0#*/} COMMAND [APP]..."
  exit 1
fi

cmd=$1; shift

apps=$@
if [ $# -eq 0 ]; then
  apps=$(find -mindepth 1 -maxdepth 1 -type d -not -path '*/\.*' -exec basename {} \; | sort)
fi

scriptdir=`dirname $0`
"$scriptdir"/commands/$cmd $apps
