#!/bin/bash

if [ $# -eq 0 ]; then
  echo "Usage: ${0#*/} COMMAND [APP]..."
  exit 1
fi

function getScriptDir {
  SOURCE="$1"
  # resolve $SOURCE until the file is no longer a symlink
  while [ -h "$SOURCE" ]; do
    DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
    SOURCE="$(readlink "$SOURCE")"
    # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
    [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE"
  done
  DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
  echo $DIR
}

cmd=$1; shift

apps=$@
if [ $# -eq 0 ]; then
  apps=$(find -mindepth 1 -maxdepth 1 -type d -not -path '*/\.*' -exec basename {} \; | sort)
fi

scriptdir=`getScriptDir "$0"`
"$scriptdir"/commands/$cmd $apps
