#!/bin/bash

SAVEIFS=$IFS
IFS=$(echo -en "\n\b")

for app in "$@"
do
  app=${app/\//}
  path=`./path $app`
  for localfile in $(find $app -type f)
  do
    realfile=$path/${localfile#$app/}
    cp $realfile $localfile
  done
done

IFS=$SAVEIFS
