#!/bin/bash

app="$1"
app=${app/\//}
user_path_sh=./path.user

if [ -f $user_path_sh ]; then
  user_path=`$user_path_sh $app`
  if [ -n "$user_path" ]; then
    echo $user_path
    exit
  fi
fi

case $app in
  *)
    echo ~
    ;;
esac
